In [40]:
import kagglehub
path = kagglehub.dataset_download("skywescar/lifesnaps-fitbit-dataset")
print("Path to dataset files:", path)

Path to dataset files: /Users/apple/.cache/kagglehub/datasets/skywescar/lifesnaps-fitbit-dataset/versions/1

In [41]:
from pathlib import Path
import kagglehub
import pandas as pd
path = kagglehub.dataset_download("skywescar/lifesnaps-fitbit-dataset")  
root = Path(path)
files = sorted(root.rglob("*.csv"))
for i, p in enumerate(files):
    print(i, p.relative_to(root), f"{p.stat().st_size/1e6:.1f} MB")

0 rais_anonymized/csv_rais_anonymized/daily_fitbit_sema_df_unprocessed.csv 2.1 MB
1 rais_anonymized/csv_rais_anonymized/hourly_fitbit_sema_df_unprocessed.csv 21.1 MB
2 rais_anonymized/scored_surveys/breq.csv 0.0 MB
3 rais_anonymized/scored_surveys/panas.csv 0.0 MB
4 rais_anonymized/scored_surveys/personality.csv 0.0 MB
5 rais_anonymized/scored_surveys/stai.csv 0.0 MB
6 rais_anonymized/scored_surveys/ttm.csv 0.0 MB

In [42]:
KEY = "daily"   

matches = [p for p in files if KEY in p.name.lower()]
print("matches:", [m.name for m in matches])
f = matches[0]

df = pd.read_csv(f, low_memory=False)
print(f.name, "->", df.shape)

signals = ["heart", "rmssd", "bpm", "sleep", "step", "spo2", "stress", "eda", "temp"]
cols = [c for c in df.columns if any(s in c.lower() for s in signals)]
print(f"\n{len(df.columns)} columns total. Signal-like columns, share missing:")
print(df[cols].isna().mean().round(2).to_string())
df.head()

matches: ['daily_fitbit_sema_df_unprocessed.csv']
daily_fitbit_sema_df_unprocessed.csv -> (7410, 63)

63 columns total. Signal-like columns, share missing:
nightly_temperature            0.55
rmssd                          0.67
spo2                           0.83
full_sleep_breathing_rate      0.66
stress_score                   0.75
sleep_points_percentage        0.75
daily_temperature_variation    0.55
bpm                            0.35
sleep_duration                 0.52
minutesToFallAsleep            0.52
minutesAsleep                  0.52
sleep_efficiency               0.52
sleep_deep_ratio               0.56
sleep_wake_ratio               0.56
sleep_light_ratio              0.56
sleep_rem_ratio                0.56
steps                          0.36
step_goal                      0.74
step_goal_label                0.74

,Unnamed: 0,id,date,nightly_temperature,nremhr,rmssd,spo2,full_sleep_breathing_rate,stress_score,sleep_points_percentage,...,TENSE/ANXIOUS,TIRED,ENTERTAINMENT,GYM,HOME,HOME_OFFICE,OTHER,OUTDOORS,TRANSIT,WORK/SCHOOL
0,0,621e2e8e67b776a24055b564,2021-05-24,34.137687,57.432,89.603,NaN,14.8,78.0,0.833333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,621e2e8e67b776a24055b564,2021-05-25,33.794544,57.681,94.303,NaN,15.8,80.0,0.833333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,2,621e2e8e67b776a24055b564,2021-05-26,34.611011,57.481,119.212,NaN,14.6,84.0,0.966667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,3,621e2e8e67b776a24055b564,2021-05-27,34.408304,57.493,111.709,NaN,14.8,82.0,0.933333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,4,621e2e8e67b776a24055b564,2021-05-28,34.178922,56.750,103.034,NaN,15.2,81.0,0.866667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [43]:
from ucimlrepo import fetch_ucirepo 
cdc_diabetes_health_indicators = fetch_ucirepo(id=891) 
X = cdc_diabetes_health_indicators.data.features 
y = cdc_diabetes_health_indicators.data.targets 
print(cdc_diabetes_health_indicators.metadata) 
print(cdc_diabetes_health_indicators.variables)

{'uci_id': 891, 'name': 'CDC Diabetes Health Indicators', 'repository_url': 'https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators', 'data_url': 'https://archive.ics.uci.edu/static/public/891/data.csv', 'abstract': 'The Diabetes Health Indicators Dataset contains healthcare statistics and lifestyle survey information about people in general along with their diagnosis of diabetes. The 35 features consist of some demographics, lab test results, and answers to survey questions for each patient. The target variable for classification is whether a patient has diabetes, is pre-diabetic, or healthy. ', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Tabular', 'Multivariate'], 'num_instances': 253680, 'num_features': 21, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Sex', 'Age', 'Education Level', 'Income'], 'target_col': ['Diabetes_binary'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2017, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C53919', 'creators': [], 'intro_paper': {'ID': 308, 'type': 'NATIVE', 'title': 'Incidence of End-Stage Renal Disease Attributed to Diabetes Among Persons with Diagnosed Diabetes — United States and Puerto Rico, 2000–2014', 'authors': 'Nilka Rios Burrows, MPH; Israel Hora, PhD; Linda S. Geiss, MA; Edward W. Gregg, PhD; Ann Albright, PhD', 'venue': 'Morbidity and Mortality Weekly Report', 'year': 2017, 'journal': None, 'DOI': None, 'URL': 'https://www.cdc.gov/mmwr/volumes/66/wr/mm6643a2.htm', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Dataset link: https://www.cdc.gov/brfss/annual_data/annual_2014.html', 'purpose': 'To better understand the relationship between  lifestyle and diabetes in the US', 'funded_by': 'The CDC', 'instances_represent': 'Each row represents a person participating in this study.', 'recommended_data_splits': 'Cross validation or a fixed train-test split could be used.', 'sensitive_data': '- Gender\n- Income\n- Education level', 'preprocessing_description': 'Bucketing of age', 'variable_info': '- Diabetes diagnosis\n- Demographics (race, sex)\n- Personal information (income, educations)\n- Health history (drinking, smoking, mental health, physical health)', 'citation': None}, 'external_url': 'https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset'}
                    name     role     type      demographic  \
0                     ID       ID  Integer             None
1        Diabetes_binary   Target   Binary             None
2                 HighBP  Feature   Binary             None
3               HighChol  Feature   Binary             None
4              CholCheck  Feature   Binary             None
5                    BMI  Feature  Integer             None
6                 Smoker  Feature   Binary             None
7                 Stroke  Feature   Binary             None
8   HeartDiseaseorAttack  Feature   Binary             None
9           PhysActivity  Feature   Binary             None
10                Fruits  Feature   Binary             None
11               Veggies  Feature   Binary             None
12     HvyAlcoholConsump  Feature   Binary             None
13         AnyHealthcare  Feature   Binary             None
14           NoDocbcCost  Feature   Binary             None
15               GenHlth  Feature  Integer             None
16              MentHlth  Feature  Integer             None
17              PhysHlth  Feature  Integer             None
18              DiffWalk  Feature   Binary             None
19                   Sex  Feature   Binary              Sex
20                   Age  Feature  Integer              Age
21             Education  Feature  Integer  Education Level
22                Income  Feature  Integer           Income

                                          description units missing_values
0                                          Patient ID  None             no
1         0 = no diabetes 1 = prediabetes or diabetes  None             no
2                          0 = no high BP 1 = high BP  None             no
3        0 = no high cholesterol 1 = high cholesterol  None             no
4   0 = no cholesterol check in 5 years 1 = yes ch...  None             no
5                                     Body Mass Index  None             no
6   Have you smoked at least 100 cigarettes in you...  None             no
7        (Ever told) you had a stroke. 0 = no 1 = yes  None             no
8   coronary heart disease (CHD) or myocardial inf...  None             no
9   physical activity in past 30 days - not includ...  None             no
10  Consume Fruit 1 or more times per day 0 = no 1...  None             no
11  Consume Vegetables 1 or more times per day 0 =...  None             no
12  Heavy drinkers (adult men having more than 14 ...  None             no
13  Have any kind of health care coverage, includi...  None             no
14  Was there a time in the past 12 months when yo...  None             no
15  Would you say that in general your health is: ...  None             no
16  Now thinking about your mental health, which i...  None             no
17  Now thinking about your physical health, which...  None             no
18  Do you have serious difficulty walking or clim...  None             no
19                                0 = female 1 = male  None             no
20  13-level age category (_AGEG5YR see codebook) ...  None             no
21  Education level (EDUCA see codebook) scale 1-6...  None             no
22  Income scale (INCOME2 see codebook) scale 1-8 ...  None             no

In [44]:
df.describe()

,Unnamed: 0,nightly_temperature,nremhr,rmssd,spo2,full_sleep_breathing_rate,stress_score,sleep_points_percentage,exertion_points_percentage,responsiveness_points_percentage,...,TENSE/ANXIOUS,TIRED,ENTERTAINMENT,GYM,HOME,HOME_OFFICE,OTHER,OUTDOORS,TRANSIT,WORK/SCHOOL
count,7410.00000,3359.000000,2475.000000,2475.000000,1270.000000,2495.000000,1876.000000,1876.000000,1876.000000,1876.000000,...,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000
mean,3704.50000,33.771650,62.714134,40.021232,95.893228,14.836954,64.181237,0.653998,0.632689,0.641791,...,0.220087,0.384279,0.084716,0.007424,0.772926,0.099563,0.024454,0.151092,0.087773,0.265502
std,2139.22708,0.905129,11.051482,21.305442,1.114339,3.774846,28.470995,0.303243,0.295897,0.293409,...,0.414396,0.486531,0.278520,0.085859,0.419032,0.299482,0.154488,0.358216,0.283026,0.441697
min,0.00000,25.518333,0.000000,0.000000,89.400000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1852.25000,33.305913,57.434500,25.442000,95.200000,13.200000,67.000000,0.633333,0.600000,0.633333,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3704.50000,33.887166,63.146000,34.072000,95.900000,15.000000,75.000000,0.733333,0.725000,0.766667,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5556.75000,34.342720,69.192000,48.723000,96.700000,17.000000,80.000000,0.833333,0.825000,0.833333,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,7409.00000,36.684793,92.547000,122.089000,100.000000,29.800000,94.000000,1.000000,1.000000,0.966667,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [45]:
from ucimlrepo import fetch_ucirepo 
heart_failure_clinical_records = fetch_ucirepo(id=519) 
X = heart_failure_clinical_records.data.features 
y = heart_failure_clinical_records.data.targets 
print(heart_failure_clinical_records.metadata) 
print(heart_failure_clinical_records.variables)

{'uci_id': 519, 'name': 'Heart Failure Clinical Records', 'repository_url': 'https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records', 'data_url': 'https://archive.ics.uci.edu/static/public/519/data.csv', 'abstract': 'This dataset contains the medical records of 299 patients who had heart failure, collected during their follow-up period, where each patient profile has 13 clinical features.', 'area': 'Health and Medicine', 'tasks': ['Classification', 'Regression', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 299, 'num_features': 12, 'feature_types': ['Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['death_event'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2020, 'last_updated': 'Mon Feb 26 2024', 'dataset_doi': '10.24432/C5Z89R', 'creators': [], 'intro_paper': {'ID': 286, 'type': 'NATIVE', 'title': 'Machine learning can predict survival of patients with heart failure from serum creatinine and ejection fraction alone', 'authors': 'D. Chicco, Giuseppe Jurman', 'venue': 'BMC Medical Informatics and Decision Making', 'year': 2020, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/e64579d8593140396b518682bb3a47ba246684eb', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': '32013925', 'pmcid': None}, 'additional_info': {'summary': 'A detailed description of the dataset can be found in the Dataset section of the following paper: \r\n\r\nDavide Chicco, Giuseppe Jurman: "Machine learning can predict survival of patients with heart failure from serum creatinine and ejection fraction alone". BMC Medical Informatics and Decision Making 20, 16 (2020). https://doi.org/10.1186/s12911-020-1023-5 \r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Thirteen (13) clinical features:\n\n- age: age of the patient (years)\n- anaemia: decrease of red blood cells or hemoglobin (boolean)\n- creatinine phosphokinase  (CPK): level of the CPK enzyme in the blood (mcg/L)\n- diabetes: if the patient has diabetes (boolean)\n- ejection fraction: percentage of blood leaving the heart at each contraction  (percentage)\n- high blood pressure: if the patient has hypertension (boolean)\n- platelets: platelets in the blood (kiloplatelets/mL)\n- sex: woman or man (binary)\n- serum creatinine: level of serum creatinine in the blood (mg/dL)\n- serum sodium: level of serum sodium in the blood (mEq/L)\n- smoking: if the patient smokes or not (boolean)\n- time: follow-up period (days)\n- [target] death event: if the patient died during the follow-up period (boolean)\n\nFor more information, please check Table 1, Table 2, and Table 3 of the following paper: \n\nDavide Chicco, Giuseppe Jurman: "Machine learning can predict survival of patients with heart failure from serum creatinine and ejection fraction alone". BMC Medical Informatics and Decision Making 20, 16 (2020). https://doi.org/10.1186/s12911-020-1023-5 \n', 'citation': None}}
                        name     role        type demographic  \
0                        age  Feature     Integer         Age
1                    anaemia  Feature      Binary        None
2   creatinine_phosphokinase  Feature     Integer        None
3                   diabetes  Feature      Binary        None
4          ejection_fraction  Feature     Integer        None
5        high_blood_pressure  Feature      Binary        None
6                  platelets  Feature  Continuous        None
7           serum_creatinine  Feature  Continuous        None
8               serum_sodium  Feature     Integer        None
9                        sex  Feature      Binary         Sex
10                   smoking  Feature      Binary        None
11                      time  Feature     Integer        None
12               death_event   Target      Binary        None

                                          description             units  \
0                                  age of the patient             years
1           decrease of red blood cells or hemoglobin              None
2                level of the CPK enzyme in the blood             mcg/L
3                         if the patient has diabetes              None
4   percentage of blood leaving the heart at each ...                 %
5                     if the patient has hypertension              None
6                              platelets in the blood  kiloplatelets/mL
7              level of serum creatinine in the blood             mg/dL
8                  level of serum sodium in the blood             mEq/L
9                                        woman or man              None
10                       if the patient smokes or not              None
11                                   follow-up period              days
12    if the patient died during the follow-up period              None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no

In [46]:
df.describe()

,Unnamed: 0,nightly_temperature,nremhr,rmssd,spo2,full_sleep_breathing_rate,stress_score,sleep_points_percentage,exertion_points_percentage,responsiveness_points_percentage,...,TENSE/ANXIOUS,TIRED,ENTERTAINMENT,GYM,HOME,HOME_OFFICE,OTHER,OUTDOORS,TRANSIT,WORK/SCHOOL
count,7410.00000,3359.000000,2475.000000,2475.000000,1270.000000,2495.000000,1876.000000,1876.000000,1876.000000,1876.000000,...,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000
mean,3704.50000,33.771650,62.714134,40.021232,95.893228,14.836954,64.181237,0.653998,0.632689,0.641791,...,0.220087,0.384279,0.084716,0.007424,0.772926,0.099563,0.024454,0.151092,0.087773,0.265502
std,2139.22708,0.905129,11.051482,21.305442,1.114339,3.774846,28.470995,0.303243,0.295897,0.293409,...,0.414396,0.486531,0.278520,0.085859,0.419032,0.299482,0.154488,0.358216,0.283026,0.441697
min,0.00000,25.518333,0.000000,0.000000,89.400000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1852.25000,33.305913,57.434500,25.442000,95.200000,13.200000,67.000000,0.633333,0.600000,0.633333,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3704.50000,33.887166,63.146000,34.072000,95.900000,15.000000,75.000000,0.733333,0.725000,0.766667,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,5556.75000,34.342720,69.192000,48.723000,96.700000,17.000000,80.000000,0.833333,0.825000,0.833333,...,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,7409.00000,36.684793,92.547000,122.089000,100.000000,29.800000,94.000000,1.000000,1.000000,0.966667,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [47]:
#  import libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

In [48]:
df = pd.read_csv('/Users/apple/Downloads/diabetes_prediction_dataset.csv')
df.head(10)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
5,Female,20.0,0,0,never,27.32,6.6,85,0
6,Female,44.0,0,0,never,19.31,6.5,200,1
7,Female,79.0,0,0,No Info,23.86,5.7,85,0
8,Male,42.0,0,0,never,33.64,4.8,145,0
9,Female,32.0,0,0,never,27.32,5.0,100,0

In [49]:
df = pd.read_csv('/Users/apple/Downloads/heart_2020_cleaned.csv')
df.head(10)

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
5,Yes,28.87,Yes,No,No,6.0,0.0,Yes,Female,75-79,Black,No,No,Fair,12.0,No,No,No
6,No,21.63,No,No,No,15.0,0.0,No,Female,70-74,White,No,Yes,Fair,4.0,Yes,No,Yes
7,No,31.64,Yes,No,No,5.0,0.0,Yes,Female,80 or older,White,Yes,No,Good,9.0,Yes,No,No
8,No,26.45,No,No,No,0.0,0.0,No,Female,80 or older,White,"No, borderline diabetes",No,Fair,5.0,No,Yes,No
9,No,40.69,No,No,No,0.0,0.0,Yes,Male,65-69,White,No,Yes,Good,10.0,No,No,No

In [50]:
import pandas as pd
import os
print("cwd:", os.getcwd())
print("DATA_DIR:", DATA_DIR.resolve(), "| exists:", DATA_DIR.exists())
print("CSVs there:", [p.name for p in DATA_DIR.glob("*.csv")] if DATA_DIR.exists() else "folder missing")
DATA_DIR = Path("/Users/apple/<folder from step 2>")
heart_files = list(DATA_DIR.glob("heart*cleaned*.csv", case_sensitive=False))
diabetes_files = list(DATA_DIR.glob("diabetes_prediction_dataset*.csv", case_sensitive=False))  # adjust to your filename

cwd: /Users/apple/Desktop/Digi_twin.ipnyb
DATA_DIR: /Users/apple/Downloads | exists: True
CSVs there: ['diabetes_prediction_dataset.csv', 'heart_2020_cleaned.csv']

In [51]:
from pathlib import Path
import numpy as np
import pandas as pd

DATA_DIR = Path.home() / "Downloads"
rng = np.random.default_rng(42)

diabetes_df = pd.read_csv(DATA_DIR / "diabetes_prediction_dataset.csv")
heart_df = pd.read_csv(DATA_DIR / "heart_2020_cleaned.csv")
print("diabetes:", diabetes_df.shape, "| heart:", heart_df.shape)

AGE_BINS = [17, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 200]
AGE_LABELS = ["18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54",
              "55-59", "60-64", "65-69", "70-74", "75-79", "80 or older"]
GEN = {"Poor": 0, "Fair": 1, "Good": 2, "Very good": 3, "Excellent": 4}
yn = lambda s: (s == "Yes").astype(int)

base = diabetes_df[diabetes_df.gender.isin(["Female", "Male"]) & (diabetes_df.age >= 18)].copy()
base["sex"] = base.gender
base["age_band"] = pd.cut(np.floor(base.age), AGE_BINS, labels=AGE_LABELS).astype(str)
base["diab"] = base.diabetes.astype(int)
base["hd"] = base.heart_disease.astype(int)
base["bmi_key"] = base.bmi + rng.normal(0, 0.75, len(base))  


donor = pd.DataFrame({
    "sex": heart_df.Sex, "age_band": heart_df.AgeCategory,
    "diab": heart_df.Diabetic.str.startswith("Yes").astype(int),
    "hd": yn(heart_df.HeartDisease),
    "bmi_key": heart_df.BMI, "donor_bmi": heart_df.BMI,
    "physical_activity": yn(heart_df.PhysicalActivity), "alcohol": yn(heart_df.AlcoholDrinking),
    "stroke": yn(heart_df.Stroke), "kidney_disease": yn(heart_df.KidneyDisease),
    "asthma": yn(heart_df.Asthma), "diff_walking": yn(heart_df.DiffWalking),
    "bad_physical_days": heart_df.PhysicalHealth, "bad_mental_days": heart_df.MentalHealth,
    "gen_health": heart_df.GenHealth.map(GEN), "sleep_hours": heart_df.SleepTime,
    "skin_cancer": yn(heart_df.SkinCancer), 
    "bad_physical_days": heart_df.PhysicalHealth, "bad_mental_days": heart_df.MentalHealth,
    "gen_health": heart_df.GenHealth.map(GEN), "sleep_hours": heart_df.SleepTime,
}).sort_values("bmi_key")

merged = pd.merge_asof(base.sort_values("bmi_key"), donor, on="bmi_key",
                       by=["sex", "age_band", "diab", "hd"], direction="nearest")
n0 = len(merged)
merged = merged.dropna(subset=["gen_health"])
print(f"unmatched (no donor in block): {n0 - len(merged)} of {n0}")
merged["bmi_gap"] = (merged.bmi - merged.donor_bmi).abs()
print("median BMI gap:", round(merged.bmi_gap.median(), 2))
merged = merged.drop(columns=["sex", "age_band", "diab", "hd", "bmi_key", "donor_bmi"])
merged = merged.sample(frac=1, random_state=42).reset_index(drop=True)
merged.insert(0, "patient_id", merged.index)

merged.to_csv("merged_cohort.csv", index=False)
print(merged.shape, "->", Path("merged_cohort.csv").resolve())
print(merged.groupby("diabetes")[["gen_health", "bad_physical_days", "sleep_hours"]].mean().round(2))
merged.head()

diabetes: (100000, 9) | heart: (319795, 18)
unmatched (no donor in block): 0 of 82767
median BMI gap: 0.5
(82767, 22) -> /Users/apple/Desktop/Digi_twin.ipnyb/merged_cohort.csv
          gen_health  bad_physical_days  sleep_hours
diabetes
0               2.73               2.91         7.04
1               1.88               6.56         7.09

,patient_id,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,...,stroke,kidney_disease,asthma,diff_walking,bad_physical_days,bad_mental_days,gen_health,sleep_hours,skin_cancer,bmi_gap
0,0,Female,22.0,0,0,not current,27.32,4.5,160,0,...,0,0,0,0,0.0,0.0,4,6.0,0,1.02
1,1,Female,60.0,0,0,No Info,39.93,5.7,130,1,...,0,0,1,1,30.0,20.0,1,6.0,0,0.11
2,2,Male,69.0,0,0,No Info,31.28,5.0,126,0,...,0,0,0,0,2.0,0.0,2,6.0,1,0.48
3,3,Female,31.0,0,0,never,21.95,4.5,126,0,...,0,0,1,0,3.0,15.0,2,7.0,0,0.54
4,4,Female,61.0,0,0,No Info,34.51,6.1,200,0,...,0,0,0,0,0.0,0.0,3,6.0,0,0.31

In [53]:
import pandas as pd
import numpy as np

# 1. Load the Fitbit data (using the path you provided)
fitbit_file = "/Users/apple/.cache/kagglehub/datasets/skywescar/lifesnaps-fitbit-dataset/versions/1/rais_anonymized/csv_rais_anonymized/daily_fitbit_sema_df_unprocessed.csv"
fitbit_df = pd.read_csv(fitbit_file, low_memory=False)

# 2. Inspect the actual column names to confirm the ID column
print("First 10 columns:", fitbit_df.columns[:10].tolist())
# You should see 'id' (lowercase) in this list. 
# If it is named something else like 'user_id', change the code below accordingly.

# 3. Define features and Aggregate using the correct column name 'id'
fitbit_features = [
    'nightly_temperature', 'nremhr', 'rmssd', 'spo2', 
    'full_sleep_breathing_rate', 'stress_score', 
    'sleep_points_percentage', 'TENSE/ANXIOUS', 'TIRED', 'ENTERTAINMENT'
]

# Group by 'id' (lowercase)
fitbit_agg = fitbit_df.groupby('id')[fitbit_features].mean().reset_index()

# Rename 'id' to 'fitbit_id' so it doesn't clash when merging later
fitbit_agg = fitbit_agg.rename(columns={'id': 'fitbit_id'})

print(f"Aggregated {len(fitbit_agg)} unique Fitbit users.")

First 10 columns: ['Unnamed: 0', 'id', 'date', 'nightly_temperature', 'nremhr', 'rmssd', 'spo2', 'full_sleep_breathing_rate', 'stress_score', 'sleep_points_percentage']
Aggregated 71 unique Fitbit users.

In [56]:
import pandas as pd
import numpy as np
fitbit_file = "/Users/apple/.cache/kagglehub/datasets/skywescar/lifesnaps-fitbit-dataset/versions/1/rais_anonymized/csv_rais_anonymized/daily_fitbit_sema_df_unprocessed.csv"
fitbit_df = pd.read_csv(fitbit_file, low_memory=False)

fitbit_features = [
    'nightly_temperature', 'nremhr', 'rmssd', 'spo2', 
    'full_sleep_breathing_rate', 'stress_score', 
    'sleep_points_percentage', 'TENSE/ANXIOUS', 'TIRED', 'ENTERTAINMENT'
]
fitbit_agg = fitbit_df.groupby('id')[fitbit_features].mean().reset_index()
fitbit_agg = fitbit_agg.rename(columns={'id': 'fitbit_id'})

In [57]:
clinical_df = pd.read_csv('merged_cohort.csv')
np.random.seed(42)  # For reproducibility
unique_ids = fitbit_agg['fitbit_id'].unique()
clinical_df['temp_fitbit_id'] = np.random.choice(unique_ids, size=len(clinical_df))

print("temp_fitbit_id" in clinical_df.columns)

True

In [58]:
final_master = pd.merge(
    clinical_df,
    fitbit_agg,
    left_on='temp_fitbit_id',
    right_on='fitbit_id',
    how='left'
)

final_master = final_master.drop(columns=['temp_fitbit_id', 'fitbit_id'])

print(f"Final dataset shape: {final_master.shape}")
print(final_master[['age', 'diabetes', 'stress_score', 'spo2', 'TENSE/ANXIOUS']].head())

Final dataset shape: (82767, 32)
    age  diabetes  stress_score       spo2  TENSE/ANXIOUS
0  22.0         0          40.7        NaN            NaN
1  60.0         1           NaN  96.108333       0.000000
2  69.0         0           NaN        NaN       0.000000
3  31.0         0           NaN        NaN       0.150000
4  61.0         0           NaN        NaN       0.098361

In [59]:
# Print the shape (rows, columns)
print(f"Total Rows: {final_master.shape[0]}")
print(f"Total Columns: {final_master.shape[1]}")

Total Rows: 82767
Total Columns: 32

In [60]:
# Print all column names
print(final_master.columns.tolist())

['patient_id', 'gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes', 'physical_activity', 'alcohol', 'stroke', 'kidney_disease', 'asthma', 'diff_walking', 'bad_physical_days', 'bad_mental_days', 'gen_health', 'sleep_hours', 'skin_cancer', 'bmi_gap', 'nightly_temperature', 'nremhr', 'rmssd', 'spo2', 'full_sleep_breathing_rate', 'stress_score', 'sleep_points_percentage', 'TENSE/ANXIOUS', 'TIRED', 'ENTERTAINMENT']

In [61]:
# Show the first 5 rows, focusing on the newly merged columns
columns_to_view = ['age', 'diabetes', 'stress_score', 'spo2', 'rmssd', 'nightly_temperature', 'TENSE/ANXIOUS']
print(final_master[columns_to_view].head())

    age  diabetes  stress_score       spo2      rmssd  nightly_temperature  \
0  22.0         0          40.7        NaN        NaN            33.660808
1  60.0         1           NaN  96.108333        NaN            33.098254
2  69.0         0           NaN        NaN  74.383567                  NaN
3  31.0         0           NaN        NaN  38.531434            33.956454
4  61.0         0           NaN        NaN  50.950000            34.164753

   TENSE/ANXIOUS
0            NaN
1       0.000000
2       0.000000
3       0.150000
4       0.098361

In [62]:
fitbit_features = [
    'nightly_temperature', 'nremhr', 'rmssd', 'spo2', 
    'full_sleep_breathing_rate', 'stress_score', 
    'sleep_points_percentage', 'TENSE/ANXIOUS', 'TIRED', 'ENTERTAINMENT'
]

print("Missing values in Fitbit columns:")
print(final_master[fitbit_features].isna().sum())

Missing values in Fitbit columns:
nightly_temperature           8017
nremhr                       32506
rmssd                        32506
spo2                         49774
full_sleep_breathing_rate    32506
stress_score                 39718
sleep_points_percentage      39718
TENSE/ANXIOUS                 9454
TIRED                         9454
ENTERTAINMENT                 9454
dtype: int64

In [63]:
final_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82767 entries, 0 to 82766
Data columns (total 32 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   patient_id                 82767 non-null  int64
 1   gender                     82767 non-null  object
 2   age                        82767 non-null  float64
 3   hypertension               82767 non-null  int64
 4   heart_disease              82767 non-null  int64
 5   smoking_history            82767 non-null  object
 6   bmi                        82767 non-null  float64
 7   HbA1c_level                82767 non-null  float64
 8   blood_glucose_level        82767 non-null  int64
 9   diabetes                   82767 non-null  int64
 10  physical_activity          82767 non-null  int64
 11  alcohol                    82767 non-null  int64
 12  stroke                     82767 non-null  int64
 13  kidney_disease             82767 non-null  int64
 14  asthma                     82767 non-null  int64
 15  diff_walking               82767 non-null  int64
 16  bad_physical_days          82767 non-null  float64
 17  bad_mental_days            82767 non-null  float64
 18  gen_health                 82767 non-null  int64
 19  sleep_hours                82767 non-null  float64
 20  skin_cancer                82767 non-null  int64
 21  bmi_gap                    82767 non-null  float64
 22  nightly_temperature        74750 non-null  float64
 23  nremhr                     50261 non-null  float64
 24  rmssd                      50261 non-null  float64
 25  spo2                       32993 non-null  float64
 26  full_sleep_breathing_rate  50261 non-null  float64
 27  stress_score               43049 non-null  float64
 28  sleep_points_percentage    43049 non-null  float64
 29  TENSE/ANXIOUS              73313 non-null  float64
 30  TIRED                      73313 non-null  float64
 31  ENTERTAINMENT              73313 non-null  float64
dtypes: float64(17), int64(13), object(2)
memory usage: 20.2+ MB

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

print("1. Loading clinical cohort...")
# Load the file you created earlier
clinical_df = pd.read_csv('merged_cohort.csv')

print("2. Loading and aggregating Fitbit data...")
fitbit_file = "/Users/apple/.cache/kagglehub/datasets/skywescar/lifesnaps-fitbit-dataset/versions/1/rais_anonymized/csv_rais_anonymized/daily_fitbit_sema_df_unprocessed.csv"
fitbit_df = pd.read_csv(fitbit_file, low_memory=False)

fitbit_features = [
    'nightly_temperature', 'nremhr', 'rmssd', 'spo2', 
    'full_sleep_breathing_rate', 'stress_score', 
    'sleep_points_percentage', 'TENSE/ANXIOUS', 'TIRED', 'ENTERTAINMENT'
]

fitbit_agg = fitbit_df.groupby('id')[fitbit_features].mean().reset_index()
fitbit_agg = fitbit_agg.rename(columns={'id': 'fitbit_id'})

print("3. Merging datasets...")
np.random.seed(42)
unique_ids = fitbit_agg['fitbit_id'].unique()
clinical_df['temp_fitbit_id'] = np.random.choice(unique_ids, size=len(clinical_df))

final_master = pd.merge(
    clinical_df, 
    fitbit_agg, 
    left_on='temp_fitbit_id', 
    right_on='fitbit_id', 
    how='left'
)

print("4. Cleaning up and adding patient_id...")
final_master = final_master.drop(columns=['temp_fitbit_id', 'fitbit_id'])

# CRITICAL: Add the patient_id column needed for the Streamlit Dashboard
if 'patient_id' not in final_master.columns:
    final_master.insert(0, 'patient_id', final_master.index)

print("5. Saving to CSV...")
output_filename = 'FINAL_dataset_with_fitbit.csv'
final_master.to_csv(output_filename, index=False)

print(f"✅ File successfully saved! Location: {Path(output_filename).resolve()}")
print(f"📊 Shape: {final_master.shape[0]} rows and {final_master.shape[1]} columns")

1. Loading clinical cohort...
2. Loading and aggregating Fitbit data...
3. Merging datasets...
4. Cleaning up and adding patient_id...
5. Saving to CSV...
✅ File successfully saved! Location: /Users/apple/Desktop/Digi_twin.ipnyb/FINAL_dataset_with_fitbit.csv
📊 Shape: 82767 rows and 32 columns

In [4]:
import os
from pathlib import Path

output_filename = 'FINAL_dataset_with_fitbit.csv'
final_master.to_csv(output_filename, index=False)
file_path = Path(output_filename).resolve()
print(f"File successfully saved!")
print(f"Location: {file_path}")
print(f" Shape: {final_master.shape[0]} rows and {final_master.shape[1]} columns")

File successfully saved!
Location: /Users/apple/Desktop/Digi_twin.ipnyb/FINAL_dataset_with_fitbit.csv
 Shape: 82767 rows and 32 columns

In [6]:
import pandas as pd
df = pd.read_csv('FINAL_dataset_with_fitbit.csv')
print(df[['patient_id', 'age', 'diabetes', 'stress_score']].head())

   patient_id   age  diabetes  stress_score
0           0  22.0         0          40.7
1           1  60.0         1           NaN
2           2  69.0         0           NaN
3           3  31.0         0           NaN
4           4  61.0         0           NaN